name: Build and Deploy to Kind and Portainer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/docker-treino:latest

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/docker-treino:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Kind
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: v0.11.1

    - name: Create Kind cluster
      run: kind create cluster --name kind-cluster

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: v1.20.0

    - name: Deploy to Kind
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
